name: trello nestJS CI

on:
  workflow_dispatch:
  push:
    branches: [CICD]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [CICD, CICD]

jobs:
  ci-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20 # 설치 할 Node.js 버전 지정
          cache: 'npm' # npm 사용 시 'npm'

      # 의존성 패키지 설치하기
      - name: Install dependencies
        run: |


          # package-lock.json 파일에 저장 된 버전 정보와 동일하게 설치
           npm ci
